"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 15:28:41.597418
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cinemas')),
    sa.UniqueConstraint('name', name=op.f('uq_cinemas_name'))
    )
    with op.batch_alter_table('cinemas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cinemas_city'), ['city'], unique=False)

    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    op.create_table('holidays',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('day', name=op.f('pk_holidays'))
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('age_rating', sa.Enum('P', 'K', 'T13', 'T16', 'T18', name='agerating', native_enum=False, length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movies'))
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_release_date'), ['release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)

    op.create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('seat_type', sa.Enum('standard', 'vip', 'couple', name='seattype', native_enum=False, length=20), nullable=True),
    sa.Column('day_type', sa.Enum('weekday', 'weekend', 'holiday', name='daytype', native_enum=False, length=20), nullable=True),
    sa.Column('format', sa.Enum('2D', '3D', 'IMAX', name='screenformat', native_enum=False, length=20), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('surcharge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_rules'))
    )
    op.create_table('auditoriums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('cleaning_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_auditoriums_cinema_id_cinemas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoriums')),
    sa.UniqueConstraint('cinema_id', 'name', name=op.f('uq_auditoriums_cinema_id'))
    )
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoriums_cinema_id'), ['cinema_id'], unique=False)

    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genres_genre_id_genres'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genres_movie_id_movies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('pk_movie_genres'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('customer', 'staff', 'admin', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_users_cinema_id_cinemas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auditorium_id', sa.Integer(), nullable=False),
    sa.Column('row_label', sa.String(length=3), nullable=False),
    sa.Column('col_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('standard', 'vip', 'couple', name='seattype', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditoriums.id'], name=op.f('fk_seats_auditorium_id_auditoriums'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seats')),
    sa.UniqueConstraint('auditorium_id', 'row_label', 'col_number', name=op.f('uq_seats_auditorium_id'))
    )
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seats_auditorium_id'), ['auditorium_id'], unique=False)

    op.create_table('showtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('auditorium_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('format', sa.Enum('2D', '3D', 'IMAX', name='screenformat', native_enum=False, length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='showtimestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['auditorium_id'], ['auditoriums.id'], name=op.f('fk_showtimes_auditorium_id_auditoriums')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_showtimes_movie_id_movies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_showtimes'))
    )
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.create_index('ix_showtimes_auditorium_starts', ['auditorium_id', 'starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_showtimes_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_showtimes_starts_at'), ['starts_at'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('online', 'counter', name='saleschannel', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', 'refunded', name='reservationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_reservations_created_by_id_users')),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], name=op.f('fk_reservations_showtime_id_showtimes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reservations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations')),
    sa.UniqueConstraint('code', name=op.f('uq_reservations_code'))
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_showtime_id'), ['showtime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_user_id'), ['user_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_invoices_reservation_id_reservations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('number', name=op.f('uq_invoices_number')),
    sa.UniqueConstraint('reservation_id', name=op.f('uq_invoices_reservation_id'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('vnpay', 'momo', 'cash', 'mock', name='paymentprovider', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', 'refunded', name='paymentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('provider_txn_id', sa.String(length=100), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_payments_reservation_id_reservations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key')),
    sa.UniqueConstraint('provider_txn_id', name=op.f('uq_payments_provider_txn_id'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_reservation_id'), ['reservation_id'], unique=False)

    op.create_table('showtime_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showtime_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'held', 'sold', 'blocked', name='showtimeseatstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_showtime_seats_reservation_id_reservations')),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], name=op.f('fk_showtime_seats_seat_id_seats')),
    sa.ForeignKeyConstraint(['showtime_id'], ['showtimes.id'], name=op.f('fk_showtime_seats_showtime_id_showtimes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_showtime_seats')),
    sa.UniqueConstraint('showtime_id', 'seat_id', name=op.f('uq_showtime_seats_showtime_id'))
    )
    with op.batch_alter_table('showtime_seats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_showtime_seats_reservation_id'), ['reservation_id'], unique=False)
        batch_op.create_index('ix_showtime_seats_status_held_until', ['status', 'held_until'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('showtime_seat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('valid', 'used', 'cancelled', 'refunded', name='ticketstatus', native_enum=False, length=20), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_id'], ['users.id'], name=op.f('fk_tickets_checked_in_by_id_users')),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], name=op.f('fk_tickets_reservation_id_reservations')),
    sa.ForeignKeyConstraint(['showtime_seat_id'], ['showtime_seats.id'], name=op.f('fk_tickets_showtime_seat_id_showtime_seats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('code', name=op.f('uq_tickets_code'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_reservation_id'), ['reservation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_reservation_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('showtime_seats', schema=None) as batch_op:
        batch_op.drop_index('ix_showtime_seats_status_held_until')
        batch_op.drop_index(batch_op.f('ix_showtime_seats_reservation_id'))

    op.drop_table('showtime_seats')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_reservation_id'))

    op.drop_table('payments')
    op.drop_table('invoices')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_user_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_status'))
        batch_op.drop_index(batch_op.f('ix_reservations_showtime_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('showtimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_showtimes_starts_at'))
        batch_op.drop_index(batch_op.f('ix_showtimes_movie_id'))
        batch_op.drop_index('ix_showtimes_auditorium_starts')

    op.drop_table('showtimes')
    with op.batch_alter_table('seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seats_auditorium_id'))

    op.drop_table('seats')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('movie_genres')
    with op.batch_alter_table('auditoriums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoriums_cinema_id'))

    op.drop_table('auditoriums')
    op.drop_table('price_rules')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_title'))
        batch_op.drop_index(batch_op.f('ix_movies_release_date'))

    op.drop_table('movies')
    op.drop_table('holidays')
    op.drop_table('genres')
    with op.batch_alter_table('cinemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cinemas_city'))

    op.drop_table('cinemas')
    # ### end Alembic commands ###
